server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 30000
    use-read-only-response-cache: false
